import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import{Bell,Calendar,CheckCircle2,ChevronRight,Clock,FileUp,Home,Plane,ShieldCheck,User,Settings,AlertTriangle,MessageCircle,RefreshCcw,Wifi,MapPin}from'lucide-react';import{api,getApiUrl,setApiUrl}from'./api.js';import{crew,roster,notifications}from'./demo.js';import'./styles.css';
const tabs=[{k:'home',l:'Home',i:Home},{k:'roster',l:'Roster',i:Calendar},{k:'actions',l:'Actions',i:CheckCircle2},{k:'wallet',l:'Wallet',i:ShieldCheck},{k:'alerts',l:'Alerts',i:Bell},{k:'settings',l:'Settings',i:Settings}];
function App(){const[active,setActive]=useState('home');const[profile,setProfile]=useState(crew);const[toast,setToast]=useState('Demo mode ready');useEffect(()=>{api('getMobileHome',{crewId:crew.crewId}).then(r=>{if(r?.crew)setProfile(r.crew);setToast(r?.ok?'Connected to backend':'Demo mode ready')})},[]);return <div className="phoneShell"><div className="status"><span>9:41</span><b>ACMS Crew</b><span>{toast.includes('Connected')?'Live':'Demo'}</span></div><main>{active==='home'&&<HomeScreen profile={profile} setActive={setActive}/>} {active==='roster'&&<RosterScreen/>}{active==='actions'&&<ActionsScreen setToast={setToast}/>} {active==='wallet'&&<WalletScreen/>}{active==='alerts'&&<AlertsScreen/>}{active==='settings'&&<SettingsScreen setToast={setToast}/>}</main><nav>{tabs.map(t=>{const I=t.i;return <button className={active===t.k?'on':''} onClick={()=>setActive(t.k)} key={t.k}><I size={20}/><span>{t.l}</span></button>})}</nav></div>}
function Card({children,cls=''}){return <section className={'card '+cls}>{children}</section>}
function HomeScreen({profile,setActive}){return <><div className="hero"><div><small>M01 Crew Home</small><h1>Hi, {profile.name}</h1><p>{profile.rank} · {profile.base} · {profile.fleet}</p></div><div className="avatar">AR</div></div><Card cls="today"><span className="pill fly">Next Duty</span><h2>{profile.nextDuty}</h2><p><Clock size={16}/> Report {profile.report} · Check-in {profile.checkWindow}</p><div className="actions"><button onClick={()=>setActive('actions')}>Check In</button><button className="ghost" onClick={()=>setActive('roster')}>View Roster</button></div></Card><div className="quickGrid"><Quick title="Acknowledge" sub="1 pending"/><Quick title="Leave" sub="Apply / status"/><Quick title="Absence" sub="Report sick"/><Quick title="Help" sub="Ask chatbot"/></div></>}
function Quick({title,sub}){return <Card cls="quick"><b>{title}</b><span>{sub}</span><ChevronRight size={16}/></Card>}
function RosterScreen(){return <><Title id="M02" title="My Roster Calendar"/><div className="seg"><button className="on">Week</button><button>Month</button><button>List</button></div>{roster.map((r,i)=><Card cls="rosterItem" key={i}><span className={'type '+r.type.toLowerCase()}>{r.type}</span><div><h3>{r.title}</h3><p>{r.date} · {r.time}</p><small>{r.status}</small></div></Card>)}</>}
function ActionsScreen({setToast}){async function doAction(action,msg){setToast('Submitting...');const res=await api(action,{crewId:crew.crewId,flight:'FY3124',lat:3.1319,lng:101.6841});setToast(res?.ok?msg:'Saved in demo mode')}return <><Title id="M04/M05/M07/M08/M10/M11" title="Crew Actions"/><ActionCard icon={<CheckCircle2/>} title="Acknowledge Roster" body="Confirm you have seen published roster v3." btn="Acknowledge" onClick={()=>doAction('acknowledgeRoster','Roster acknowledged')}/><ActionCard icon={<MapPin/>} title="Duty Check-In" body="One-tap check-in with location/Wi-Fi/device log." btn="Check in now" onClick={()=>doAction('postCheckIn','Check-in posted')}/><ActionCard icon={<AlertTriangle/>} title="Report Absence & Upload MC" body="Report sick/emergency and add MC link/photo reference." btn="Report absence" onClick={()=>doAction('submitAbsence','Absence case opened')}/><ActionCard icon={<Calendar/>} title="Apply Leave" body="Select leave range and submit for supervisor approval." btn="Apply leave" onClick={()=>doAction('submitLeave','Leave submitted')}/><ActionCard icon={<RefreshCcw/>} title="Standby Call-Up" body="Accept/reject standby activation with countdown evidence." btn="Accept call-up" onClick={()=>doAction('acceptStandby','Standby accepted')}/></>}
function ActionCard({icon,title,body,btn,onClick}){return <Card cls="action"><div className="actIcon">{icon}</div><div><h3>{title}</h3><p>{body}</p><button onClick={onClick}>{btn}</button></div></Card>}
function WalletScreen(){return <><Title id="M12/M13" title="Training & Validity Wallet"/><Card cls="profile"><div className="avatar big">AR</div><h2>A. Rahman</h2><p>Captain · KUL · ATR72</p></Card>{['License valid · 210 days','Medical valid · 42 days to expiry','SEP training valid · 118 days','CRM valid · 221 days','Route recency KUL-PEN · current'].map((x,i)=><Card cls="wallet" key={x}><ShieldCheck size={20}/><div><b>{x.split(' · ')[0]}</b><p>{x.split(' · ')[1]}</p></div><span className={i===1?'warn':'ok'}>{i===1?'Renew':'OK'}</span></Card>)}<button className="wide"><FileUp size={18}/> Upload document update</button></>}
function AlertsScreen(){return <><Title id="M14/M15/M16/M17" title="Notifications & Help"/>{notifications.map(n=><Card cls="notif" key={n.title}><Bell size={20}/><div><h3>{n.title}</h3><p>{n.body}</p><small>{n.time} ago</small></div><span>{n.action}</span></Card>)}<Card cls="chat"><MessageCircle/><h3>Crew Chatbot</h3><p>Ask about roster, leave, check-in, training expiry or support tickets.</p><input placeholder="Ask: what is my next duty?"/><button>Ask</button></Card></>}
function SettingsScreen({setToast}){const[url,setUrl]=useState(getApiUrl());function save(){setApiUrl(url);setToast('Backend URL saved')}return <><Title id="M18" title="Settings & Security"/><Card><label>Apps Script Web App URL</label><textarea value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://script.google.com/macros/s/.../exec"/><button onClick={save}>Save Backend URL</button></Card><Card cls="settings"><p><Wifi size={18}/> Geo/Wi-Fi check-in enabled</p><p><ShieldCheck size={18}/> Device binding active</p><p><Bell size={18}/> Push/email notifications enabled</p></Card></>}
function Title({id,title}){return <div className="title"><small>{id}</small><h1>{title}</h1></div>}
createRoot(document.getElementById('root')).render(<App/>);
